[package]
name = "pebble-game-io"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
gmeta.workspace = true
gstd.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true